#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
os = "#ACB0BE"
closer = "p:os"
pink = "#F5C2E7"
lavender = "#B4BEFE"
blue = "#89B4FA"

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "p:os"
style = "plain"
template = "{{.Icon}} "
type = "os"

[[blocks.segments]]
foreground = "p:blue"
style = "plain"
template = "{{ .UserName }}@{{ .HostName }} "
type = "session"

[[blocks.segments]]
foreground = "p:pink"
style = "powerline"
template = " {{ .Path }} "
type = "path"

[blocks.segments.properties]
folder_icon = ""
home_icon = "~"
style = "full"

[[blocks.segments]]
foreground = "p:lavender"
template = "{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}"
style = "plain"
type = "git"

[blocks.segments.properties]
branch_icon = " "
cherry_pick_icon = " "
commit_icon = " "
fetch_status = true
fetch_upstream_icon = true
merge_icon = " "
no_commits_icon = " "
rebase_icon = " "
revert_icon = " "
tag_icon = " "

[[blocks.segments]]
style = "plain"
foreground = "p:closer"
template = ""
type = "text"

[[blocks]]
alignment = "right"
type = "rprompt"

[[blocks.segments]]
foreground = "p:pink"
style = "plain"
template = "  {{ .FormattedMs }} "
type = "executiontime"

[blocks.segments.properties]
style = "roundrock"
